use PROJECT;
CREATE TABLE BOOKINGS(
	BOOKING_ID INT IDENTITY(1,1) PRIMARY KEY,
	REGION NVARCHAR(50) NOT NULL,
	CITY NVARCHAR(50) NOT NULL,
	HOTEL NVARCHAR(50) NOT NULL,
	FULL_NAME NVARCHAR(100) NOT NULL,
	EMAIL NVARCHAR(100) NOT NULL,
	CHECK_IN DATE NOT NULL,
	CHECK_OUT DATE NOT NULL,
	GUESTS INT NOT NULL,
	PRICE_PER_NIGHT INT NOT NULL,
	BOOKING_DATE DATETIME DEFAULT GETDATE()
);

USE PROJECT;
SELECT *
FROM BOOKINGS;

USE PROJECT;
DROP TABLE BOOKINGS;

USE PROJECT;
TRUNCATE TABLE BOOKINGS;